CREATE TABLE Roles
(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Activo BIT NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE Usuarios
(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL,
	Fecha_Nacimiento DATE NOT NULL,
	Clave NVARCHAR(MAX) NOT NULL,
	Mail NVARCHAR(50) NOT NULL,
	Id_Rol INT NOT NULL,
	Activo BIT NOT NULL,
	Codigo INT,
	PRIMARY KEY (Id),
	FOREIGN KEY (Id_Rol) REFERENCES Roles(Id)
)

CREATE TABLE Productos
(
	Id INT NOT NULL IDENTITY(1,1),
	Descripcion NVARCHAR(150) NOT NULL,
	Precio DECIMAL (18,0) NOT NULL,
	Stock INT NOT NULL,
	Imagen NVARCHAR(MAX) NOT NULL,
	Activo bit NOT NULL,
	PRIMARY KEY (Id)
)
